### ISSUE TITLE
前后端分离docker部署上传接口返回127.0.0.1

### ISSUE THREAD

**Issue by cooolr** [kingwrcy/mblog-backend#3]
使用docker镜像前后端分离部署时，上传图片时，上传接口 `/api/resource/upload`  返回的资源地址是127.0.0.1的，而不是后端公网地址
```
{"data":[{"publicId":"PdsKeBmtNGYFceluyXzH","url":"http://127.0.0.1:38321/api/resource/PdsKeBmtNGYFceluyXzH"}],"code":0,"msg":""}
```
后端部署时是不是应该指定一个资源url。

**Comment by cooolr** [comment]
好的，遇到新的问题，上传成功后返回的url访问报错资源不存在
/api/resource/wPURJOqnKlNPrNmajNcX

{"data":null,"code":2,"msg":"resource不存在"}

**Comment by kingwrcy** [comment]
1. 看看你映射的upload目录有没有你传的文件？
2. 看看表t_resource有没有你这个public_id的记录？
如果都没有，那应该是没上传成功.

**Comment by cooolr** [comment]
> 1. 看看你映射的upload目录有没有你传的文件？
> 2. 看看表t_resource有没有你这个public_id的记录？
>    如果都没有，那应该是没上传成功.

1. 映射的目录有这个文件;
2. 表t_resource有这个记录，但是public_id和resource_url的哈希没对应上
| uTpjrIZHVPSfWAGdIAqp | 2296063 | /api/resource/wPURJOqnKlNPrNmajNcX |
